CREATE DATABASE minha_aplicacao;

USE minha_aplicacao;

CREATE TABLE usuarios(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
sobrenome VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
cpf VARCHAR(11) NOT NULL UNIQUE,
endereco VARCHAR(255) NOT NULL,
CEP VARCHAR(8) NOT NULL
);